### ISSUE TITLE
Would you please update the training methods?

### ISSUE THREAD

**Issue by prnvjb** [CVML-Detection/Densely-packed-Object-Detection-via-Hard-Negative-Aware-Anchor-Attention#1]
Hi,
Thanks for open-sourcing it.
I see in the readme that there is only test.py but missing train.py.
I would like to know the training py file.

Appreciate your novelty.
Thanks.

**Comment by nuggy875** [comment]
Hi, thank you for interest in our work.
Could you give us your e-mail address? Then we'll send you our train.py code.

Thanks :)

**Comment by MMarvasti** [comment]
Hi,
Nice work. Would you release your training code or send it to me as well?
Thanks.

**Comment by YukiItoh0519** [comment]
Hello,
I sent you an email the other day.
I would be happy if you could check it out.

Thanks.

**Comment by csm-kr** [comment]
hello. Thank you for your interest in our work.
Due to a system migration issue, the train code cannot be found for the time being.
We will update as soon as it is restored.

thank you
